baseURL = "https://kusen-pintu.bangunan.co/"
languageCode = "id"
title = "Kusen Pintu dan Jendela | Pasang Kusen Pintu dan Jendela Alumunium Murah"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Pembuatan Kusen Pintu dan Jendela Alumunium - Berpengalaman, Profesional, dan Berkualitas"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual kusen pintu", "jual kusen jendela", "pasang kusen pintu alumunium", "pasang kusen jendela alumunium", "kontraktor kusen pintu", "kontraktor kusen jendela", "alumunium murah", "pembuatan kusen pintu", "pembuatan kusen jendela", "pemasangan kusen pintu"]
  base_price = 500000
  price_range = 200000
  free_shipping = true
  materials = [
  "Kusen Pintu Alumunium",
  "Kusen Jendela Alumunium",
  "Kusen Pintu Kayu",
  "Kusen Jendela Kayu",
  "Kusen Pintu PVC",
  "Kusen Jendela PVC"
  ]
  categories = ["Kusen Pintu", "Kusen Jendela", "Alumunium", "Kayu", "PVC"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk barang dengan cacat produksi.",
  "Barang yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
]

# Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jasa Pasang Kusen Pintu dan Jendela Alumunium"
  hero_description = "Kami menawarkan berbagai pilihan kusen pintu dan jendela alumunium berkualitas, dengan desain modern dan material tahan lama. Solusi terbaik untuk mempercantik dan memperkuat struktur rumah atau kantor Anda dengan pemasangan yang rapi dan berpengalaman."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog"

# Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan layanan pembuatan kusen pintu dan jendela alumunium dengan berbagai pilihan desain, bahan berkualitas, dan harga terjangkau. Layanan pengukuran dan pemasangan dengan konsultasi gratis untuk membantu Anda menemukan pilihan terbaik."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "Kusen-pintu.bangunan.co menawarkan berbagai pilihan kusen pintu dan jendela alumunium berkualitas dengan desain modern dan material yang tahan lama. Kami mengutamakan kepuasan pelanggan dengan pemasangan yang rapi, cepat, dan profesional."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Deni|Rudi|Hendra|Agus|Wawan|Rio}"
  message = "{Saya menggunakan layanan pemasangan kusen pintu alumunium dari kusen-pintu.bangunan.co untuk {rumah|proyek|gedung|renovasi} saya, dan hasilnya {sangat memuaskan|luar biasa|memenuhi harapan}. {Pemasangannya|Proses instalasinya} {rapi|bersih|teratur} dan kualitas kusennya {sangat baik|tahan lama|berkualitas tinggi}.|Layanan kusen-pintu.bangunan.co {sangat profesional|berkualitas} dengan hasil yang {rapi|teratur} dan kualitas kusen yang {terjamin|hebat}.}"
  response = "{Terima kasih atas {kepercayaan|pilihan} Anda! Kami senang dapat menyediakan kusen pintu {berkualitas|terbaik} untuk {rumah|proyek} Anda.|Kami {menghargai|berterima kasih atas} kepercayaan Anda!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Lina|Fitri|Diah|Nur|Maya}"
  message = "{kusen-pintu.bangunan.co sangat {membantu|mempermudah} saya dalam {memilih|menentukan} dan memasang kusen pintu alumunium untuk {rumah|proyek} saya. Hasilnya {sangat memuaskan|luar biasa|memenuhi harapan} dan sesuai dengan {kebutuhan|ekspektasi|rencana} saya.|Saya {sangat puas|terkesan} dengan bantuan kusen-pintu.bangunan.co dalam pemasangan kusen pintu yang {rapi|teratur} dan sesuai dengan keinginan saya.}"
  response = "{Kami sangat {menghargai|berterima kasih atas} ulasan Anda. Senang mendengar bahwa Anda puas dengan {layanan|pelayanan} dan produk kusen pintu kami.|Terima kasih atas ulasannya, kami senang dapat memenuhi harapan Anda.}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Faisal|Galih|Rizal|Bambang|Ali|Fajar|Toni}"
  message = "{Kusen pintu alumunium dari kusen-pintu.bangunan.co {sangat estetis|modern|minimalis} dan {kokoh|kuat|tahan lama}. Cocok untuk proyek {perumahan|gedung|konstruksi} saya, dan proses pemasangannya juga {cepat|efisien|profesional}.|Saya {sangat puas|terkesan} dengan kusen pintu alumunium dari kusen-pintu.bangunan.co. Hasilnya {rapi|kokoh|teratur} dan pemasangan berjalan dengan {cepat|profesional|efisien}.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan kusen pintu berkualitas dengan {layanan terbaik|pelayanan prima}.|Kami sangat senang mendengar bahwa Anda puas dengan hasil kusen pintu dari kami.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Toni|Hendra|Dedi|Gilang|Ari|Wawan|Gani|Yudi}"
  message = "{Saya {sangat puas|terkesan|senang} dengan kusen pintu dari kusen-pintu.bangunan.co. {Kualitas|Mutu} kusennya {sangat baik|terbaik|terjamin} dan pemasangannya {cepat|efisien|rapi} untuk proyek saya.|Kusen pintu dari kusen-pintu.bangunan.co {berkualitas|handal|kokoh} dengan pemasangan yang {cepat|efisien|rapi} sesuai kebutuhan proyek saya.}"
  response = "{Senang mendengar Anda puas dengan kusen pintu kami. Terima kasih atas {kepercayaannya|pilihan Anda}!|Kami sangat menghargai kepercayaan Anda. Terima kasih sudah memilih layanan kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan kusen-pintu.bangunan.co {sangat memuaskan|luar biasa|terbaik}. Kusen pintu alumunium yang saya {pasang|gunakan|terapkan} {sangat berkualitas|berkualitas tinggi|bermutu} dan sesuai dengan {harapan|ekspektasi|rencana} saya.|Saya {senang|terkesan|puas} dengan pelayanan dari kusen-pintu.bangunan.co. Kusennya {berkualitas|tahan lama|modern} dan sesuai dengan keinginan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani} Anda mewujudkan proyek dengan kusen pintu terbaik.|Kami sangat menghargai ulasan Anda. Terima kasih telah mempercayakan proyek Anda kepada kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Deni|Rizal|Rio|Benny|Yanto|Galih|Toni|Faisal|Wawan}"
  message = "{Kusen pintu dari kusen-pintu.bangunan.co sangat {sesuai|tepat|cocok} dengan kebutuhan proyek {renovasi|rumah|gedung|perumahan} saya. Proses pemasangannya {cepat|aman|efisien} dan {terjamin|rapi|bersih}.|Saya {puas|terkesan|senang} dengan kusen pintu dari kusen-pintu.bangunan.co. Layanan pemasangannya {profesional|cepat|teratur} dan sesuai dengan kebutuhan proyek saya.}"
  response = "{Kami {senang|gembira} mendengar bahwa Anda puas dengan kusen pintu kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan proyek Anda kepada kami. Kami senang Anda puas dengan hasilnya.}"
  rating = 5

[[params.tabelItems]]
  name = "Kusen Aluminium 4 Inch"
  price = "130.000/m"
[[params.tabelItems]]
  name = "Kusen Aluminium 3 Inch"
  price = "100.000/m"
[[params.tabelItems]]
  name = "Kusen Aluminium 4 Inch (Lokal)"
  price = "110.000/m"
[[params.tabelItems]]
  name = "Kusen Aluminium 3 Inch (Lokal)"
  price = "90.000/m"
[[params.tabelItems]]
  name = "Kusen Aluminium 4 Inch (Variasi)"
  price = "100.000/m"
[[params.tabelItems]]
  name = "Kusen Aluminium 3 Inch (Variasi)"
  price = "130.000/m"
[[params.tabelItems]]
  name = "Pintu Aluminium 4 Inch"
  price = "130.000/m"
[[params.tabelItems]]
  name = "Pintu Aluminium 3 Inch"
  price = "100.000/m"

[params.appliList]
  "Kusen Aluminium 4 Inch" = "digunakan pada pintu utama, ruangan yang membutuhkan keamanan tinggi"
  "Kusen Aluminium 3 Inch" = "cocok untuk ruangan dalam rumah, seperti kamar tidur atau ruang kerja"
  "Kusen Aluminium 4 Inch (Lokal)" = "ideal untuk area yang membutuhkan ventilasi baik dan pencahayaan"
  "Kusen Aluminium 3 Inch (Lokal)" = "sering digunakan untuk jendela di ruang tamu"
  "Kusen Aluminium 4 Inch (Variasi)" = "bisa digunakan untuk berbagai desain arsitektur"
  "Kusen Aluminium 3 Inch (Variasi)" = "ideal untuk proyek yang memerlukan kecepatan dan biaya yang lebih rendah"
  "Pintu Aluminium 4 Inch" = "interior rumah, ruang kerja"
  "Pintu Aluminium 3 Inch" = "ruang tamu, ruang makan"

[params.kegunaanList]
  "Kusen Aluminium 4 Inch" = "memberikan kekuatan dan ketahanan terhadap cuaca, ideal untuk pintu eksterior"
  "Kusen Aluminium 3 Inch" = "menawarkan solusi hemat biaya untuk jendela dan pintu interior"
  "Kusen Aluminium 4 Inch (Lokal)" = "cocok untuk bangunan komersial yang membutuhkan tampilan profesional"
  "Kusen Aluminium 3 Inch (Lokal)" = "mendukung desain modern dengan penggunaan yang fleksibel"
  "Kusen Aluminium 4 Inch (Variasi)" = "memberikan opsi tambahan untuk variasi desain"
  "Kusen Aluminium 3 Inch (Variasi)" = "cocok untuk penggunaan sehari-hari yang ekonomis"
  "Pintu Aluminium 4 Inch" = "cocok untuk interior modern di rumah dengan daya tahan yang baik"
  "Pintu Aluminium 3 Inch" = "digunakan untuk ruang makan atau ruang tamu, memberikan tampilan yang elegan dan minimalis"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Jasa Pembuatan dan Pasang Kusen Pintu dan Jendela Alumunium | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"